package com.cms.pojo.log;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.util.Date;

/**
 * LogLogin generated by hbm2java
 */

//@Table(name = "log_login")
@Data
public class LogLogin implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
   //@GeneratorColumn(title = "ID")
    private Long id;
   //@GeneratorColumn(title = "站点", condition = true)
    @JsonIgnore
    private short siteId;
   //@GeneratorColumn(title = "用户名", condition = true, like = true)
    private String name;
   //@GeneratorColumn(title = "用户", condition = true)
    private Long userId;
   //@GeneratorColumn(title = "IP", condition = true, like = true)
    private String ip;
   //@GeneratorColumn(title = "登录渠道", condition = true)
    private String channel;
   //@GeneratorColumn(title = "登录结果", condition = true)
    private boolean result;
   //@GeneratorColumn(title = "登录日期", condition = true, order = true)
    private Date createDate;
   //@GeneratorColumn(title = "错误密码")
    private String errorPassword;

    public LogLogin() {
    }

    public LogLogin(short siteId, String name, String ip, String channel, boolean result, Date createDate) {
        this.siteId = siteId;
        this.name = name;
        this.ip = ip;
        this.channel = channel;
        this.result = result;
        this.createDate = createDate;
    }

    public LogLogin(short siteId, String name, Long userId, String ip, String channel, boolean result, Date createDate,
            String errorPassword) {
        this.siteId = siteId;
        this.name = name;
        this.userId = userId;
        this.ip = ip;
        this.channel = channel;
        this.result = result;
        this.createDate = createDate;
        this.errorPassword = errorPassword;
    }


}
