package com.cms.pojo.log;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.util.Date;

/**
 * LogOperate generated by hbm2java
 */

//@Table(name = "log_operate")
@Data
public class LogOperate implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
   //@GeneratorColumn(title = "ID")
    private Long id;
   //@GeneratorColumn(title = "站点", condition = true)
    @JsonIgnore
    private short siteId;
   //@GeneratorColumn(title = "用户", condition = true)
    private Long userId;
   //@GeneratorColumn(title = "渠道", condition = true)
    private String channel;
   //@GeneratorColumn(title = "操作", condition = true)
    private String operate;
   //@GeneratorColumn(title = "IP", condition = true)
    private String ip;
   //@GeneratorColumn(title = "操作日期", condition = true, order = true)
    private Date createDate;
   //@GeneratorColumn(title = "内容", condition = true, like = true)
    private String content;

    public LogOperate() {
    }

    public LogOperate(short siteId, String channel, String operate, Date createDate, String content) {
        this.siteId = siteId;
        this.channel = channel;
        this.operate = operate;
        this.createDate = createDate;
        this.content = content;
    }

    public LogOperate(short siteId, Long userId, String channel, String operate, String ip, Date createDate, String content) {
        this.siteId = siteId;
        this.userId = userId;
        this.channel = channel;
        this.operate = operate;
        this.ip = ip;
        this.createDate = createDate;
        this.content = content;
    }


}
