package com.cms.pojo.log;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.util.Date;

/**
 * LogTask generated by hbm2java
 */

//@Table(name = "log_task")
@Data
public class LogTask implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
   //@GeneratorColumn(title = "ID")
    private Long id;
   //@GeneratorColumn(title = "站点", condition = true)
    @JsonIgnore
    private short siteId;
   //@GeneratorColumn(title = "任务", condition = true)
    private int taskId;
   //@GeneratorColumn(title = "开始日期", condition = true, order = true)
    private Date begintime;
   //@GeneratorColumn(title = "结束时间")
    private Date endtime;
   //@GeneratorColumn(title = "结果", condition = true)
    private boolean success;
   //@GeneratorColumn(title = "日志")
    private String result;

    public LogTask() {
    }

    public LogTask(short siteId, int taskId, Date begintime, boolean success) {
        this.siteId = siteId;
        this.taskId = taskId;
        this.begintime = begintime;
        this.success = success;
    }

    public LogTask(Long id, short siteId, int taskId, Date begintime, Date endtime, boolean success) {
        this.id = id;
        this.siteId = siteId;
        this.taskId = taskId;
        this.begintime = begintime;
        this.endtime = endtime;
        this.success = success;
    }

    public LogTask(short siteId, int taskId, Date begintime, Date endtime, boolean success, String result) {
        this.siteId = siteId;
        this.taskId = taskId;
        this.begintime = begintime;
        this.endtime = endtime;
        this.success = success;
        this.result = result;
    }



}
