package com.cms.pojo.log;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.util.Date;

/**
 * LogUpload generated by hbm2java
 */

//@Table(name = "log_upload")
@Data
public class LogUpload implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
   //@GeneratorColumn(title = "ID")
    private Long id;
   //@GeneratorColumn(title = "站点", condition = true)
    @JsonIgnore
    private short siteId;
   //@GeneratorColumn(title = "用户", condition = true)
    private long userId;
   //@GeneratorColumn(title = "渠道", condition = true)
    private String channel;
   //@GeneratorColumn(title = "原文件名", condition = true, like = true)
    private String originalName;
   //@GeneratorColumn(title = "文件类型", condition = true)
    private String fileType;
   //@GeneratorColumn(title = "站点", order = true)
    private long fileSize;
   //@GeneratorColumn(title = "IP")
    private String ip;
   //@GeneratorColumn(title = "操作日期", order = true)
    private Date createDate;
   //@GeneratorColumn(title = "文件路径", condition = true, like = true)
    private String filePath;

    public LogUpload() {
    }

    public LogUpload(short siteId, long userId, String channel, String fileType, long fileSize, Date createDate,
            String filePath) {
        this.siteId = siteId;
        this.userId = userId;
        this.channel = channel;
        this.fileType = fileType;
        this.fileSize = fileSize;
        this.createDate = createDate;
        this.filePath = filePath;
    }

    public LogUpload(short siteId, long userId, String channel, String originalName, String fileType, long fileSize, String ip,
            Date createDate, String filePath) {
        this.siteId = siteId;
        this.userId = userId;
        this.channel = channel;
        this.originalName = originalName;
        this.fileType = fileType;
        this.fileSize = fileSize;
        this.ip = ip;
        this.createDate = createDate;
        this.filePath = filePath;
    }


}
