package com.cms.pojo.sys;
// Generated 2016-12-15 17:52:43 by Hibernate Tools 4.3.1

import lombok.Data;

/**
 * SysAppClientId generated by hbm2java
 */
@Data
public class SysAppClientId implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private short siteId;
    private String channel;
    private String uuid;

    public SysAppClientId() {
    }

    public SysAppClientId(short siteId, String channel, String uuid) {
        this.siteId = siteId;
        this.channel = channel;
        this.uuid = uuid;
    }


    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof SysAppClientId))
            return false;
        SysAppClientId castOther = (SysAppClientId) other;

        return (this.getSiteId() == castOther.getSiteId())
                && ((this.getChannel() == castOther.getChannel()) || (this.getChannel() != null && castOther.getChannel() != null
                        && this.getChannel().equals(castOther.getChannel())))
                && ((this.getUuid() == castOther.getUuid())
                        || (this.getUuid() != null && castOther.getUuid() != null && this.getUuid().equals(castOther.getUuid())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getSiteId();
        result = 37 * result + (getChannel() == null ? 0 : this.getChannel().hashCode());
        result = 37 * result + (getUuid() == null ? 0 : this.getUuid().hashCode());
        return result;
    }

}
