package com.cms.pojo.sys;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.util.Date;

/**
 * AppClient generated by hbm2java
 */

//@Table(name = "sys_app_client")
@Data
public class SysAppClient implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
   //@GeneratorColumn(title = "ID")
    private SysAppClientId sacId;
    private Long userId;
   //@GeneratorColumn(title = "版本")
    private String clientVersion;
   //@GeneratorColumn(title = "上次登录日期", condition = true, order = true)
    private Date lastLoginDate;
   //@GeneratorColumn(title = "上次登录IP")
    private String lastLoginIp;
   //@GeneratorColumn(title = "创建日期", condition = true, order = true)
    private Date createDate;
   //@GeneratorColumn(title = "已禁用", condition = true)
    @JsonIgnore
    private boolean disabled;

    public SysAppClient() {
    }

    public SysAppClient(SysAppClientId id, Date createDate, boolean disabled) {
        this.sacId = id;
        this.createDate = createDate;
        this.disabled = disabled;
    }

    public SysAppClient(SysAppClientId id, Long userId, String clientVersion, Date lastLoginDate, String lastLoginIp,
            Date createDate, boolean disabled) {
        this.sacId = id;
        this.userId = userId;
        this.clientVersion = clientVersion;
        this.lastLoginDate = lastLoginDate;
        this.lastLoginIp = lastLoginIp;
        this.createDate = createDate;
        this.disabled = disabled;
    }


}
