package com.cms.pojo.sys;

// Generated 2016-3-2 20:42:39 by Hibernate Tools 4.3.1

import lombok.Data;


import java.util.Date;

/**
 * SysAppToken generated by hbm2java
 */

//@Table(name = "sys_app_token")
@Data
public class SysAppToken implements java.io.Serializable {


    private static final long serialVersionUID = 1L;
    private Integer id;

   //@GeneratorColumn(title = "授权验证")
    private String authToken;
   //@GeneratorColumn(title = "应用")
    private int appId;
   //@GeneratorColumn(title = "创建日期", condition = true)
    private Date createDate;
   //@GeneratorColumn(title = "过期日期", condition = true, order = true)
    private Date expiryDate;

    public SysAppToken() {
    }

    public SysAppToken(String authToken, int appId, Date createDate) {
        this.authToken = authToken;
        this.appId = appId;
        this.createDate = createDate;
    }
    public SysAppToken(String authToken, int appId, Date createDate, Date expiryDate) {
        this.authToken = authToken;
        this.appId = appId;
        this.createDate = createDate;
        this.expiryDate = expiryDate;
    }


}
