package com.cms.pojo.sys;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

/**
 * SysApp generated by hbm2java
 */

//@Table(name = "sys_app", uniqueConstraints = @UniqueConstraint(columnNames = "app_key"))
@Data
public class SysApp implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
   //@GeneratorColumn(title = "ID")
    private Integer id;
   //@GeneratorColumn(title = "站点", condition = true)
    @JsonIgnore
    private short siteId;
   //@GeneratorColumn(title = "渠道", condition = true)
    private String channel;
   //@GeneratorColumn(title = "授权KEY")
    private String appKey;
    @JsonIgnore
   //@GeneratorColumn(title = "授权密码")
    private String appSecret;
   //@GeneratorColumn(title = "授权接口")
    private String authorizedApis;
   //@GeneratorColumn(title = "过期时间")
    private Integer expiryMinutes;

    public SysApp() {
    }

    public SysApp(short siteId, String channel, String appKey, String appSecret) {
        this.siteId = siteId;
        this.channel = channel;
        this.appKey = appKey;
        this.appSecret = appSecret;
    }

    public SysApp(short siteId, String channel, String appKey, String appSecret, String authorizedApis, Integer expiryMinutes) {
        this.siteId = siteId;
        this.channel = channel;
        this.appKey = appKey;
        this.appSecret = appSecret;
        this.authorizedApis = authorizedApis;
        this.expiryMinutes = expiryMinutes;
    }


}
