package com.cms.pojo.sys;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

// Generated 2016-5-16 18:15:59 by Hibernate Tools 4.3.1

/**
 * SysConfigData generated by hbm2java
 */

//@Table(name = "sys_config_data")
@Data
public class SysConfigData implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;

   //@GeneratorColumn(title = "ID")
    private SysConfigDataId sysConfigDataId;
   //@GeneratorColumn(title = "值")
    @JsonIgnore
    private String data;

    public SysConfigData() {
    }

    public SysConfigData(SysConfigDataId id, String data) {
        this.sysConfigDataId = id;
        this.data = data;
    }


}
