package com.cms.pojo.sys;

import lombok.Data;

/**
 * SysDeptConfig generated by hbm2java
 */

//@Table(name = "sys_dept_config")
@Data
public class SysDeptConfig implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;

   //@GeneratorColumn(title = "ID")
    private SysDeptConfigId sysDeptConfigId;

    public SysDeptConfig() {
    }

    public SysDeptConfig(SysDeptConfigId id) {
        this.sysDeptConfigId = id;
    }


}
