package com.cms.pojo.sys;

import lombok.Data;


/**
 * SysDomain generated by hbm2java
 */

//@Table(name = "sys_domain")
@Data
public class SysDomain implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;

   //@GeneratorColumn(title = "域名")
    private String name;
   //@GeneratorColumn(title = "站点", condition = true)
    private short siteId;
   //@GeneratorColumn(title = "通配", condition = true)
    private boolean wild;
   //@GeneratorColumn(title = "路径")
    private String path;

    public SysDomain() {
    }

    public SysDomain(String name, short siteId, boolean wild) {
        this.name = name;
        this.siteId = siteId;
        this.wild = wild;
    }

    public SysDomain(String name, short siteId, boolean wild, String path) {
        this.name = name;
        this.siteId = siteId;
        this.wild = wild;
        this.path = path;
    }


}
