package com.cms.pojo.sys;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

/**
 * SysDept generated by hbm2java
 */

//@Table(name = "sys_dept")
@Data
public class SysDept implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
   //@GeneratorColumn(title = "ID")
    private Integer id;
   //@GeneratorColumn(title = "站点", condition = true)
    @JsonIgnore
    private short siteId;
   //@GeneratorColumn(title = "名称", condition = true, like = true)
    private String name;
   //@GeneratorColumn(title = "父部门", condition = true)
    private Integer parentId;
   //@GeneratorColumn(title = "描述")
    private String description;
   //@GeneratorColumn(title = "负责人", condition = true)
    private Long userId;
   //@GeneratorColumn(title = "最大内容置顶级别")
    private int maxSort;
   //@GeneratorColumn(title = "拥有全部分类")
    private boolean ownsAllCategory;
   //@GeneratorColumn(title = "拥有全部页面")
    private boolean ownsAllPage;
   //@GeneratorColumn(title = "拥有全部配置")
    private boolean ownsAllConfig;

    public SysDept() {
    }

    public SysDept(short siteId, String name, int maxSort, boolean ownsAllCategory, boolean ownsAllPage, boolean ownsAllConfig) {
        this.siteId = siteId;
        this.name = name;
        this.maxSort = maxSort;
        this.ownsAllCategory = ownsAllCategory;
        this.ownsAllPage = ownsAllPage;
        this.ownsAllConfig = ownsAllConfig;
    }

    public SysDept(short siteId, String name, Integer parentId, String description, Long userId, int maxSort, boolean ownsAllCategory,
            boolean ownsAllPage, boolean ownsAllConfig) {
        this.siteId = siteId;
        this.name = name;
        this.parentId = parentId;
        this.description = description;
        this.userId = userId;
        this.maxSort = maxSort;
        this.ownsAllCategory = ownsAllCategory;
        this.ownsAllPage = ownsAllPage;
        this.ownsAllConfig = ownsAllConfig;
    }


}
