package com.cms.pojo.sys;

import lombok.Data;

/**
 * SysDeptPage generated by hbm2java
 */

//@Table(name = "sys_dept_page")
@Data
public class SysDeptPage implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;

   //@GeneratorColumn(title = "ID")
    private SysDeptPageId sysDeptPageId;

    public SysDeptPage() {
    }

    public SysDeptPage(SysDeptPageId id) {
        this.sysDeptPageId = id;
    }


}
