package com.cms.pojo.sys;

import lombok.Data;

/**
 * SysDeptCategory generated by hbm2java
 */

//@Table(name = "sys_dept_category")
@Data
public class SysDeptCategory implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;

   //@GeneratorColumn(title = "ID")
    private SysDeptCategoryId sysDeptCategoryId;

    public SysDeptCategory() {
    }

    public SysDeptCategory(SysDeptCategoryId id) {
        this.sysDeptCategoryId = id;
    }



}
