package com.cms.pojo.sys;

import lombok.Data;

/**
 * SysExtend generated by hbm2java
 */

//@Table(name = "sys_extend")
@Data
public class SysExtend implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

   //@GeneratorColumn(title = "ID")
    private Integer id;
   //@GeneratorColumn(title = "扩展类型")
    private String itemType;
   //@GeneratorColumn(title = "扩展项目ID")
    private int itemId;

    public SysExtend() {
    }

    public SysExtend(String itemType, int itemId) {
        this.itemType = itemType;
        this.itemId = itemId;
    }


}
