package com.cms.pojo.sys;

import lombok.Data;

// Generated 2016-3-2 13:36:22 by Hibernate Tools 4.3.1

/**
 * SysExtendField generated by hbm2java
 */

//@Table(name = "sys_extend_field")
@Data
public class SysExtendField implements java.io.Serializable {
    
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private Integer id;

    private SysExtendFieldId sysExtendFieldId;
   //@GeneratorColumn(title = "必填")
    private boolean required;
   //@GeneratorColumn(title = "最大长度")
    private Integer maxlength;
   //@GeneratorColumn(title = "名称")
    private String name;
   //@GeneratorColumn(title = "描述")
    private String description;
   //@GeneratorColumn(title = "表单类型")
    private String inputType;
   //@GeneratorColumn(title = "默认值")
    private String defaultValue;
   //@GeneratorColumn(title = "数据字典ID")
    private Long dictionaryId;
   //@GeneratorColumn(title = "顺序", order = true)
    private int sort;

    public SysExtendField() {
    }

    public SysExtendField(SysExtendFieldId id, boolean required, String name, String inputType, int sort) {
        this.sysExtendFieldId = id;
        this.required = required;
        this.name = name;
        this.inputType = inputType;
        this.sort = sort;
    }

    public SysExtendField(SysExtendFieldId id, boolean required, Integer maxlength, String name, String description,
            String inputType, String defaultValue, Long dictionaryId, int sort) {
        this.sysExtendFieldId = id;
        this.required = required;
        this.maxlength = maxlength;
        this.name = name;
        this.description = description;
        this.inputType = inputType;
        this.defaultValue = defaultValue;
        this.dictionaryId = dictionaryId;
        this.sort = sort;
    }



}
