package com.cms.pojo.sys;

// Generated 2016-3-4 18:33:25 by Hibernate Tools 4.3.1

import lombok.Data;

import java.util.Date;

/**
 * SysEmailToken generated by hbm2java
 */

//@Table(name = "sys_email_token")
@Data
public class SysEmailToken implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;

   //@GeneratorColumn(title = "验证授权码")
    private String authToken;
   //@GeneratorColumn(title = "用户", condition = true)
    private long userId;
   //@GeneratorColumn(title = "邮件地址")
    private String email;
   //@GeneratorColumn(title = "创建日期")
    private Date createDate;
   //@GeneratorColumn(title = "过期日期")
    private Date expiryDate;

    public SysEmailToken() {
    }

    public SysEmailToken(String authToken, long userId, String email, Date createDate, Date expiryDate) {
        this.authToken = authToken;
        this.userId = userId;
        this.email = email;
        this.createDate = createDate;
        this.expiryDate = expiryDate;
    }


}
