package com.cms.pojo.sys;
// Generated 2018-6-5 18:18:57 by Hibernate Tools 5.1.6.Final

import lombok.Data;

/**
 * SysModuleLang generated by hbm2java
 */

//@Table(name = "sys_module_lang")
@Data
public class SysModuleLang implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;

   //@GeneratorColumn(title = "ID")
    private SysModuleLangId sysModuleLangId;
   //@GeneratorColumn(title = "值")
    private String value;

    public SysModuleLang() {
    }

    public SysModuleLang(SysModuleLangId id) {
        this.sysModuleLangId = id;
    }

    public SysModuleLang(SysModuleLangId id, String value) {
        this.sysModuleLangId = id;
        this.value = value;
    }



}
