package com.cms.pojo.sys;

import lombok.Data;


/**
 * SysModule generated by hbm2java
 */

//@Table(name = "sys_module")
@Data
public class SysModule implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
   //@GeneratorColumn(title = "ID")
    private String id;
   //@GeneratorColumn(title = "地址")
    private String url;
   //@GeneratorColumn(title = "授权地址")
    private String authorizedUrl;
   //@GeneratorColumn(title = "附加")
    private String attached;
   //@GeneratorColumn(title = "父模块", condition = true)
    private String parentId;
   //@GeneratorColumn(title = "是否菜单", condition = true)
    private boolean menu;
   //@GeneratorColumn(title = "排序")
    private int sort;

    public SysModule() {
    }

    public SysModule(String id, boolean menu, int sort) {
        this.id = id;
        this.menu = menu;
        this.sort = sort;
    }

    public SysModule(String id, String url, String authorizedUrl, String attached, String parentId, boolean menu,
            int sort) {
        this.id = id;
        this.url = url;
        this.authorizedUrl = authorizedUrl;
        this.attached = attached;
        this.parentId = parentId;
        this.menu = menu;
        this.sort = sort;
    }



}
