package com.cms.pojo.sys;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

/**
 * SysRole generated by hbm2java
 */

//@Table(name = "sys_role")
@Data
public class SysRole implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
   //@GeneratorColumn(title = "ID")
    private Integer id;
   //@GeneratorColumn(title = "站点", condition = true)
    @JsonIgnore
    private short siteId;
   //@GeneratorColumn(title = "名称")
    private String name;
   //@GeneratorColumn(title = "拥有全部权限")
    private boolean ownsAllRight;
   //@GeneratorColumn(title = "显示全部模块")
    private boolean showAllModule;

    public SysRole() {
    }

    public SysRole(short siteId, String name, boolean ownsAllRight, boolean showAllModule) {
        this.siteId = siteId;
        this.name = name;
        this.ownsAllRight = ownsAllRight;
        this.showAllModule = showAllModule;
    }


}
