package com.cms.pojo.sys;
// Generated 2016-11-19 15:33:56 by Hibernate Tools 4.3.1

import lombok.Data;

/**
 * SysRoleModuleId generated by hbm2java
 */
@Data
public class SysRoleModuleId implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;

   //@GeneratorColumn(title = "角色", condition = true)
    private int roleId;
   //@GeneratorColumn(title = "模块", condition = true)
    private String moduleId;

    public SysRoleModuleId() {
    }

    public SysRoleModuleId(int roleId, String moduleId) {
        this.roleId = roleId;
        this.moduleId = moduleId;
    }


    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof SysRoleModuleId))
            return false;
        SysRoleModuleId castOther = (SysRoleModuleId) other;

        return (this.getRoleId() == castOther.getRoleId())
                && ((this.getModuleId() == castOther.getModuleId()) || (this.getModuleId() != null
                        && castOther.getModuleId() != null && this.getModuleId().equals(castOther.getModuleId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getRoleId();
        result = 37 * result + (getModuleId() == null ? 0 : this.getModuleId().hashCode());
        return result;
    }

}
