package com.cms.pojo.sys;

import lombok.Data;

// Generated 2016-1-19 11:28:06 by Hibernate Tools 4.3.1

/**
 * SysRoleUser generated by hbm2java
 */

//@Table(name = "sys_role_user")
@Data
public class SysRoleUser implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;

   //@GeneratorColumn(title = "ID")
    private SysRoleUserId sysRoleUserId;

    public SysRoleUser() {
    }

    public SysRoleUser(SysRoleUserId id) {
        this.sysRoleUserId = id;
    }


}
