package com.cms.pojo.sys;

import lombok.Data;

// Generated 2016-1-19 11:28:06 by Hibernate Tools 4.3.1

/**
 * SysRoleAuthorized generated by hbm2java
 */

//@Table(name = "sys_role_authorized")
@Data
public class SysRoleAuthorized implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;

   //@GeneratorColumn(title = "ID")
    private SysRoleAuthorizedId sysRoleAuthorizedId;

    public SysRoleAuthorized() {
    }

    public SysRoleAuthorized(SysRoleAuthorizedId id) {
        this.sysRoleAuthorizedId = id;
    }



}
