package com.cms.pojo.sys;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

/**
 * SysSite generated by hbm2java
 */

//@Table(name = "sys_site")
@Data
public class SysSite implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
   //@GeneratorColumn(title = "ID")
    private Short id;
   //@GeneratorColumn(title = "父站点ID", condition = true)
    private Short parentId;
   //@GeneratorColumn(title = "名称", condition = true, like = true)
    private String name;
   //@GeneratorColumn(title = "启用静态化")
    private boolean useStatic;
   //@GeneratorColumn(title = "站点地址")
    private String sitePath;
   //@GeneratorColumn(title = "启用SSI")
    private boolean useSsi;
   //@GeneratorColumn(title = "动态站点地址")
    private String dynamicPath;
   //@GeneratorColumn(title = "禁用", condition = true)
    @JsonIgnore
    private boolean disabled;

    public SysSite() {
    }

    public SysSite(String name, boolean useStatic, String sitePath, boolean useSsi, String dynamicPath, boolean disabled) {
        this.name = name;
        this.useStatic = useStatic;
        this.sitePath = sitePath;
        this.useSsi = useSsi;
        this.dynamicPath = dynamicPath;
        this.disabled = disabled;
    }

    public SysSite(Short parentId, String name, boolean useStatic, String sitePath, boolean useSsi, String dynamicPath,
            boolean disabled) {
        this.parentId = parentId;
        this.name = name;
        this.useStatic = useStatic;
        this.sitePath = sitePath;
        this.useSsi = useSsi;
        this.dynamicPath = dynamicPath;
        this.disabled = disabled;
    }



}
