package com.cms.pojo.sys;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.util.Date;

// Generated 2016-1-19 11:28:06 by Hibernate Tools 4.3.1

/**
 * SysTask generated by hbm2java
 */

//@Table(name = "sys_task")
@Data
public class SysTask implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
   //@GeneratorColumn(title = "ID")
    private Integer id;
   //@GeneratorColumn(title = "站点", condition = true)
    @JsonIgnore
    private short siteId;
   //@GeneratorColumn(title = "任务名称")
    private String name;
   //@GeneratorColumn(title = "状态", condition = true)
    private int status;
   //@GeneratorColumn(title = "表达式")
    private String cronExpression;
   //@GeneratorColumn(title = "描述")
    private String description;
   //@GeneratorColumn(title = "任务内容")
    private String filePath;
   //@GeneratorColumn(title = "更新日期", condition = true)
    private Date updateDate;

    public SysTask() {
    }

    public SysTask(short siteId, String name, int status, String cronExpression) {
        this.siteId = siteId;
        this.name = name;
        this.status = status;
        this.cronExpression = cronExpression;
    }

    public SysTask(short siteId, String name, int status, String cronExpression, String description, String filePath,
            Date updateDate) {
        this.siteId = siteId;
        this.name = name;
        this.status = status;
        this.cronExpression = cronExpression;
        this.description = description;
        this.filePath = filePath;
        this.updateDate = updateDate;
    }


}
