package com.cms.pojo.cms;

import lombok.Data;

// Generated 2016-1-19 11:28:06 by Hibernate Tools 4.3.1

/**
 * CmsCategoryModel generated by hbm2java
 */

//@Table(name = "cms_category_model")
@Data
public class CmsCategoryModel implements java.io.Serializable {



    private static final long serialVersionUID = 1L;
//
//    private Integer id;
    private CmsCategoryModelId id;
   //@GeneratorColumn(title = "模板路径")
    private String templatePath;

    public CmsCategoryModel() {
    }





}
