package com.cms.pojo.cms;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

/**
 * CmsCategory generated by hbm2java
 */
//@Table(name = "cms_category")
@Data
public class CmsCategory implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
   //@GeneratorColumn(title = "ID")
    private Integer id;
   //@GeneratorColumn(title = "站点", condition = true)
    @JsonIgnore
    private short siteId;
   //@GeneratorColumn(title = "名称")
    private String name;
   //@GeneratorColumn(title = "父分类", condition = true)
    private Integer parentId;
   //@GeneratorColumn(title = "分类类型", condition = true)
    private Integer typeId;
   //@GeneratorColumn(title = "子分类")
    private String childIds;
   //@GeneratorColumn(title = "标签ID")
    private String tagTypeIds;
   //@GeneratorColumn(title = "编码")
    private String code;
   //@GeneratorColumn(title = "模板路径")
    @JsonIgnore
    private String templatePath;
   //@GeneratorColumn(title = "路径")
    @JsonIgnore
    private String path;
   //@GeneratorColumn(title = "外链")
    private boolean onlyUrl;
   //@GeneratorColumn(title = "有静态化")
    private boolean hasStatic;
   //@GeneratorColumn(title = "地址")
    private String url;
   //@GeneratorColumn(title = "内容路径")
    @JsonIgnore
    private String contentPath;
   //@GeneratorColumn(title = "包含子分类内容")
    private boolean containChild;
   //@GeneratorColumn(title = "每页数据")
    private Integer pageSize;
   //@GeneratorColumn(title = "允许投稿", condition = true)
    private boolean allowContribute;
   //@GeneratorColumn(title = "排序")
    private int sort;
   //@GeneratorColumn(title = "是否隐藏", condition = true)
    private boolean hidden;
   //@GeneratorColumn(title = "是否删除", condition = true)
    @JsonIgnore
    private boolean disabled;
   //@GeneratorColumn(title = "扩展ID")
    private Integer extendId;

    public CmsCategory() {
    }

    public CmsCategory(short siteId, String name, String path, boolean onlyUrl, boolean hasStatic, boolean containChild,
            boolean allowContribute, int sort, boolean hidden, boolean disabled) {
        this.siteId = siteId;
        this.name = name;
        this.path = path;
        this.onlyUrl = onlyUrl;
        this.hasStatic = hasStatic;
        this.containChild = containChild;
        this.allowContribute = allowContribute;
        this.sort = sort;
        this.hidden = hidden;
        this.disabled = disabled;
    }

    public CmsCategory(short siteId, String name, Integer parentId, Integer typeId, String childIds, String tagTypeIds,
            String code, String templatePath, String path, boolean onlyUrl, boolean hasStatic, String url, String contentPath,
            boolean containChild, Integer pageSize, boolean allowContribute, int sort, boolean hidden, boolean disabled,
            Integer extendId) {
        this.siteId = siteId;
        this.name = name;
        this.parentId = parentId;
        this.typeId = typeId;
        this.childIds = childIds;
        this.tagTypeIds = tagTypeIds;
        this.code = code;
        this.templatePath = templatePath;
        this.path = path;
        this.onlyUrl = onlyUrl;
        this.hasStatic = hasStatic;
        this.url = url;
        this.contentPath = contentPath;
        this.containChild = containChild;
        this.pageSize = pageSize;
        this.allowContribute = allowContribute;
        this.sort = sort;
        this.hidden = hidden;
        this.disabled = disabled;
        this.extendId = extendId;
    }


}
