package com.cms.pojo.cms;

import lombok.Data;

/**
 * CmsContentRelated generated by hbm2java
 */

//@Table(name = "cms_content_related")
@Data
public class CmsContentRelated implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
   //@GeneratorColumn(title = "ID")
    private Long id;
   //@GeneratorColumn(title = "内容", condition = true)
    private long contentId;
   //@GeneratorColumn(title = "推荐内容", condition = true)
    private Long relatedContentId;
   //@GeneratorColumn(title = "推荐用户", condition = true)
    private long userId;
   //@GeneratorColumn(title = "推荐地址")
    private String url;
   //@GeneratorColumn(title = "推荐标题")
    private String title;
   //@GeneratorColumn(title = "推荐描述")
    private String description;
   //@GeneratorColumn(title = "点击数", order = true)
    private int clicks;
   //@GeneratorColumn(title = "排序")
    private int sort;

    public CmsContentRelated() {
    }

    public CmsContentRelated(long contentId, long userId, int clicks, int sort) {
        this.contentId = contentId;
        this.userId = userId;
        this.clicks = clicks;
        this.sort = sort;
    }

    public CmsContentRelated(long contentId, Long relatedContentId, long userId, String url, String title, String description,
            int clicks, int sort) {
        this.contentId = contentId;
        this.relatedContentId = relatedContentId;
        this.userId = userId;
        this.url = url;
        this.title = title;
        this.description = description;
        this.clicks = clicks;
        this.sort = sort;
    }



}
