package com.cms.pojo.cms;
// Generated 2016-11-19 14:08:55 by Hibernate Tools 4.3.1

import lombok.Data;

/**
 * CmsCategoryModelId generated by hbm2java
 */
@Data
public class CmsCategoryModelId implements java.io.Serializable {


    private static final long serialVersionUID = 1L;
    private Integer id;

   //@GeneratorColumn(title = "分类", condition = true)
    private int categoryId;
   //@GeneratorColumn(title = "模型", condition = true)
    private String modelId;

    public CmsCategoryModelId() {
    }

    public CmsCategoryModelId(int categoryId, String modelId) {
        this.categoryId = categoryId;
        this.modelId = modelId;
    }


    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof CmsCategoryModelId))
            return false;
        CmsCategoryModelId castOther = (CmsCategoryModelId) other;

        return (this.getCategoryId() == castOther.getCategoryId())
                && ((this.getModelId() == castOther.getModelId()) || (this.getModelId() != null && castOther.getModelId() != null
                        && this.getModelId().equals(castOther.getModelId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getCategoryId();
        result = 37 * result + (getModelId() == null ? 0 : this.getModelId().hashCode());
        return result;
    }

}
