package com.cms.pojo.cms;

//Generated 2016-1-19 11:28:06 by Hibernate Tools 4.3.1

import lombok.Data;



/**
 * CmsContentAttribute generated by hbm2java
 */

//@Table(name = "cms_content_attribute")
@Data
public class CmsContentAttribute implements java.io.Serializable {


    private static final long serialVersionUID = 1L;
    private Integer id;

   //@GeneratorColumn(title = "内容")
    private long contentId;
   //@GeneratorColumn(title = "来源")
    private String source;
   //@GeneratorColumn(title = "来源地址")
    private String sourceUrl;
   //@GeneratorColumn(title = "扩展数据")
    private String data;
   //@GeneratorColumn(title = "文本")
    private String text;
   //@GeneratorColumn(title = "字数")
    private int wordCount;

    public CmsContentAttribute() {
    }

    public CmsContentAttribute(long contentId, int wordCount) {
        this.contentId = contentId;
        this.wordCount = wordCount;
    }
    
    public CmsContentAttribute(long contentId, String source, String sourceUrl, String data, int wordCount) {
        this.contentId = contentId;
        this.source = source;
        this.sourceUrl = sourceUrl;
        this.data = data;
        this.wordCount = wordCount;
    }

    public CmsContentAttribute(long contentId, String source, String sourceUrl, String data, String text, int wordCount) {
        this.contentId = contentId;
        this.source = source;
        this.sourceUrl = sourceUrl;
        this.data = data;
        this.text = text;
        this.wordCount = wordCount;
    }


}
