package com.cms.pojo.cms;
// Generated 2016-11-20 14:46:17 by Hibernate Tools 4.3.1

import lombok.Data;

/**
 * CmsDictionaryData generated by hbm2java
 */

//@Table(name = "cms_dictionary_data")
@Data
public class CmsDictionaryData implements java.io.Serializable {

    private Integer id;

    private static final long serialVersionUID = 1L;
    private CmsDictionaryDataId cddid;
   //@GeneratorColumn(title = "文字")
    private String text;

    public CmsDictionaryData() {
    }

    public CmsDictionaryData(CmsDictionaryDataId id, String text) {
        this.cddid = id;
        this.text = text;
    }


}
