package com.cms.pojo.cms;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.util.Date;

/**
 * CmsPlace generated by hbm2java
 */

//@Table(name = "cms_place")
@Data
public class CmsPlace implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
   //@GeneratorColumn(title = "ID")
    private Long id;
   //@GeneratorColumn(title = "站点", condition = true)
    @JsonIgnore
    private short siteId;
   //@GeneratorColumn(title = "路径", condition = true)
    private String path;
   //@GeneratorColumn(title = "推荐用户", condition = true)
    private Long userId;
   //@GeneratorColumn(title = "项目类型", condition = true)
    private String itemType;
   //@GeneratorColumn(title = "项目ID", condition = true)
    private Long itemId;
   //@GeneratorColumn(title = "标题")
    private String title;
   //@GeneratorColumn(title = "地址")
    private String url;
   //@GeneratorColumn(title = "封面图")
    private String cover;
   //@GeneratorColumn(title = "创建日期", order = true)
    private Date createDate;
   //@GeneratorColumn(title = "发布日期", condition = true, order = true)
//    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date publishDate;
   //@GeneratorColumn(title = "状态", condition = true)
    private int status;
   //@GeneratorColumn(title = "点击数", order = true)
    private int clicks;
   //@GeneratorColumn(title = "已删除", condition = true)
    @JsonIgnore
    private boolean disabled;

    public CmsPlace() {
    }

    public CmsPlace(short siteId, String path, String title, Date createDate, Date publishDate, int status, int clicks,
            boolean disabled) {
        this.siteId = siteId;
        this.path = path;
        this.title = title;
        this.createDate = createDate;
        this.publishDate = publishDate;
        this.status = status;
        this.clicks = clicks;
        this.disabled = disabled;
    }

    public CmsPlace(short siteId, String path, Long userId, String itemType, Long itemId, String title, String url, String cover,
            Date createDate, Date publishDate, int status, int clicks, boolean disabled) {
        this.siteId = siteId;
        this.path = path;
        this.userId = userId;
        this.itemType = itemType;
        this.itemId = itemId;
        this.title = title;
        this.url = url;
        this.cover = cover;
        this.createDate = createDate;
        this.publishDate = publishDate;
        this.status = status;
        this.clicks = clicks;
        this.disabled = disabled;
    }



}
