package com.cms.pojo.cms;

// Generated 2016-3-4 22:54:05 by Hibernate Tools 4.3.1

import lombok.Data;

/**
 * CmsPlaceAttribute generated by hbm2java
 */

//@Table(name = "cms_place_attribute")
@Data
public class CmsPlaceAttribute implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;

   //@GeneratorColumn(title = "分类")
    private long placeId;
   //@GeneratorColumn(title = "扩展数据")
    private String data;

    public CmsPlaceAttribute() {
    }

    public CmsPlaceAttribute(long placeId) {
        this.placeId = placeId;
    }

    public CmsPlaceAttribute(long placeId, String data) {
        this.placeId = placeId;
        this.data = data;
    }



}
